### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by TRGReal** [retrooper/graphene-cpp#1]
make chunk handler, i believe in you, there's documentation for it
https://wiki.vg/Chunk_Format#Data_structure

**Comment by TRGReal** [comment]
https://github.com/cuberite/cuberite/blob/master/src/Protocol/ChunkDataSerializer.cpp#L190
library good 1.14 serialization should be easy to do 1.17, you got this

**Comment by TRGReal** [comment]
still waiting >:(

**Comment by retrooper** [comment]
no

**Comment by TRGReal** [comment]
still waiting

**Comment by qewrwer23qf** [comment]
still waiting

**Comment by retrooper** [comment]
a
